### ISSUE TITLE
[Request] Android Unit Tests & External Git Service

### ISSUE THREAD

**Issue by Apidcloud** [jamesmontemagno/CoffeeTipper#2]
Good evening!

I know this is not the best place to ask, but I have come across your 'CI for Android' article in xamarin blog, which uses this CoffeeTipper project, and would like to know if you could make a guide on how to create unit tests on Xamarin.Android and use them on CI with git services other than github (e.g., Bitbucket).

I tried to add a UnitTest project to my Android solution, but I have to run it separately - and it's not possible to use unit tests window.

Ah, btw, the link referring to VSTS on the article is broken. It would be handy to comment on the blog :)

Sincerely,
Luís Fernandes

**Comment by jamesmontemagno** [comment]
I have update the blog link woops! 

For external git look here: https://www.visualstudio.com/en-us/docs/build/define/repository#external-git

inside of Visual Studio to make nUnit tests show up you would need to install: http://motzcod.es/post/145923658347/setting-up-visual-studio-to-run-xamarinuitests

**Comment by Apidcloud** [comment]
Should the url repository be like 'https://username@bitbucket.org/repodir/repo.git'; ? I'm not able to connect to the repo for some reason... Stuck with 'Connecting to service using credentials' message. No errors at all.

**Comment by jamesmontemagno** [comment]
http://rasmustc.com/blog/CI-VSTS-Bitbucket-And-Xamarin/
